import type { Destination } from "./types";
import { ss } from "./images";

export const destinations: Destination[] = [
  {
    slug: "varanasi",
    name: "Varanasi",
    state: "Uttar Pradesh",
    stateSlug: "uttar-pradesh",
    category: "Spiritual",
    tagline: "Where the Ganges meets eternity",
    description:
      "The oldest living city in the world. At dawn the ghats ignite with ritual, fire and prayer — an unbroken 3,000-year conversation between the living and the eternal.",
    heroImage: ss("Varanasi India Ganges ghats temple"),
    bestTime: "October to March",
    highlights: [
      "Subah-e-Banaras boat ride at sunrise",
      "Ganga Aarti at Dashashwamedh Ghat",
      "Wander the lanes of the old city",
      "Sarnath, where the Buddha first taught",
    ],
    nearby: ["allahabad", "bodh-gaya"],
  },
  {
    slug: "agra",
    name: "Agra",
    state: "Uttar Pradesh",
    stateSlug: "uttar-pradesh",
    category: "Heritage",
    tagline: "Home of the Taj Mahal",
    description:
      "A monument of white marble that changes colour with the light — Agra holds the world's greatest love letter in stone, plus two more UNESCO forts within an hour.",
    heroImage: ss("Taj Mahal Agra India sunrise"),
    bestTime: "October to March",
    highlights: [
      "Taj Mahal at sunrise",
      "Agra Fort's red sandstone ramparts",
      "Fatehpur Sikri, the abandoned Mughal city",
      "Petha and Mughlai food trail",
    ],
    nearby: ["delhi", "jaipur"],
  },
  {
    slug: "delhi",
    name: "Delhi",
    state: "Delhi",
    stateSlug: "delhi",
    category: "Culture",
    tagline: "A thousand years of empire",
    description:
      "Seven cities in one. Qutub Minar, Red Fort, Humayun's Tomb and bazaars that have traded for centuries — Delhi is layered, loud and endlessly rewarding.",
    heroImage: ss("Delhi India Red Fort gate heritage"),
    bestTime: "October to March",
    highlights: [
      "Old Delhi food walk through Chandni Chowk",
      "Humayun's Tomb at golden hour",
      "Qutub Minar and Mehrauli",
      "India Gate and the colonial Lutyens' Delhi",
    ],
    nearby: ["agra", "jaipur"],
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    stateSlug: "rajasthan",
    category: "Heritage",
    tagline: "The pink city",
    description:
      "Walled in terracotta pink, crowned by the Hawa Mahal and guarded by the Amber Fort — Jaipur is Rajasthan's majestic, colourful capital.",
    heroImage: ss("Jaipur Rajasthan India Amber Fort palace"),
    bestTime: "October to March",
    highlights: [
      "Amber Fort and the Sheesh Mahal",
      "Hawa Mahal at first light",
      "City Palace and Jantar Mantar",
      "Johari Bazaar for gemstones and textiles",
    ],
    nearby: ["jodhpur", "udaipur"],
  },
  {
    slug: "jodhpur",
    name: "Jodhpur",
    state: "Rajasthan",
    stateSlug: "rajasthan",
    category: "Heritage",
    tagline: "The blue city",
    description:
      "Indigo houses spill beneath the great Mehrangarh Fort — Jodhpur is Rajasthan's most cinematic skyline, blue against desert gold.",
    heroImage: ss("Jodhpur Rajasthan India blue city fort"),
    bestTime: "October to March",
    highlights: [
      "Mehrangarh Fort at sunset",
      "Walk the blue lanes of the old city",
      "Jaswant Thada's marble cenotaphs",
      "Umaid Bhawan Palace",
    ],
    nearby: ["jaisalmer", "jaipur"],
  },
  {
    slug: "udaipur",
    name: "Udaipur",
    state: "Rajasthan",
    stateSlug: "rajasthan",
    category: "Heritage",
    tagline: "City of lakes",
    description:
      "White palaces float on still water, ringed by the Aravalli hills — Udaipur is Rajasthan's most romantic city, and it knows it.",
    heroImage: ss("Udaipur Rajasthan India lake palace white"),
    bestTime: "September to March",
    highlights: [
      "Lake Pichola sunset boat ride",
      "City Palace's labyrinthine courtyards",
      "Jag Mandir island palace",
      "Old city bazaars and havelis",
    ],
    nearby: ["jodhpur", "pushkar"],
  },
  {
    slug: "jaisalmer",
    name: "Jaisalmer",
    state: "Rajasthan",
    stateSlug: "rajasthan",
    category: "Desert",
    tagline: "The golden city",
    description:
      "A living fort of carved sandstone rising from the Thar — Jaisalmer is where the desert begins and the stars have no competition.",
    heroImage: ss("Jaisalmer Rajasthan India golden desert fort"),
    bestTime: "October to February",
    highlights: [
      "Night in the Sam sand dunes",
      "Jaisalmer Fort's havelis",
      "Camel safari into the Thar",
      "Gadisar Lake at dusk",
    ],
    nearby: ["jodhpur", "pushkar"],
  },
  {
    slug: "pushkar",
    name: "Pushkar",
    state: "Rajasthan",
    stateSlug: "rajasthan",
    category: "Spiritual",
    tagline: "The sacred lake town",
    description:
      "One of India's holiest towns, wrapped around a single lake — Pushkar is gentle, vegetarian and famous for its November camel fair.",
    heroImage: ss("Pushkar Rajasthan India camel fair lake"),
    bestTime: "November to March",
    highlights: [
      "Pushkar Camel Fair (November)",
      "Brahma Temple, the world's only",
      "Sunset over the ghats",
      "Cafés and parikrama around the lake",
    ],
    nearby: ["jaipur", "udaipur"],
  },
  {
    slug: "srinagar",
    name: "Srinagar",
    state: "Jammu & Kashmir",
    stateSlug: "jammu-kashmir",
    category: "Mountains",
    tagline: "Shikaras on Dal Lake",
    description:
      "Houseboats, Mughal gardens and snow peaks reflected in still water — Srinagar is the valley's languid, beautiful capital.",
    heroImage: ss("Srinagar Kashmir India Dal Lake shikara"),
    bestTime: "April to October",
    highlights: [
      "Shikara ride on Dal Lake",
      "Mughal gardens of Shalimar and Nishat",
      "Old city and the Jama Masjid",
      "Pahalgam and Gulmarg day trips",
    ],
    nearby: ["gulmarg", "ladakh"],
  },
  {
    slug: "gulmarg",
    name: "Gulmarg",
    state: "Jammu & Kashmir",
    stateSlug: "jammu-kashmir",
    category: "Mountains",
    tagline: "Meadow of flowers",
    description:
      "Asia's highest gondola lifts skiers and dreamers above flower meadows to the snowline — Gulmarg is Kashmir at its most alpine.",
    heroImage: ss("Gulmarg Kashmir India meadow mountains snow"),
    bestTime: "December to March (snow), May to October (meadows)",
    highlights: [
      "Gondola to Apharwat Peak",
      "Skiing and snowboarding in winter",
      "Golf at the world's highest course",
      "Trek to Alpather Lake",
    ],
    nearby: ["srinagar", "pahalgam"],
  },
  {
    slug: "leh",
    name: "Leh",
    state: "Ladakh",
    stateSlug: "ladakh",
    category: "Adventure",
    tagline: "Capital of the high desert",
    description:
      "At 11,500 feet, Leh is where the Himalaya turns lunar — monasteries, stupas and the greatest mountain roads on earth.",
    heroImage: ss("Leh Ladakh India mountains monastery"),
    bestTime: "May to September",
    highlights: [
      "Pangong Lake via Chang La pass",
      "Nubra Valley's sand dunes and Bactrian camels",
      "Thiksey and Hemis monasteries",
      "Khardung La, one of the world's highest roads",
    ],
    nearby: ["pangong", "manali"],
  },
  {
    slug: "pangong",
    name: "Pangong Lake",
    state: "Ladakh",
    stateSlug: "ladakh",
    category: "Adventure",
    tagline: "The lake that changes colour",
    description:
      "A high-altitude lake that shifts from blue to green to violet across the day, set in the silence of the Changthang plateau.",
    heroImage: ss("Leh Ladakh India mountains monastery"),
    bestTime: "June to September",
    highlights: [
      "Camp at the lakeside",
      "Drive over Chang La pass",
      "Stargazing in the high desert",
      "Marmot spotting on the plateau",
    ],
    nearby: ["leh"],
  },
  {
    slug: "manali",
    name: "Manali",
    state: "Himachal Pradesh",
    stateSlug: "himachal-pradesh",
    category: "Adventure",
    tagline: "Gateway to the high Himalaya",
    description:
      "Pine forests, rafting rivers and mountain passes — Manali is the adventure town that launched a thousand Himalayan road trips.",
    heroImage: ss("Manali Himachal Pradesh India mountains pine"),
    bestTime: "March to June, October to January (snow)",
    highlights: [
      "Solang Valley paragliding and skiing",
      "Old Manali's cafés and temples",
      "River rafting on the Beas",
      "Rohtang Pass day trip",
    ],
    nearby: ["shimla", "rishikesh"],
  },
  {
    slug: "shimla",
    name: "Shimla",
    state: "Himachal Pradesh",
    stateSlug: "himachal-pradesh",
    category: "Mountains",
    tagline: "The colonial hill queen",
    description:
      "The old British summer capital — colonial churches, a Mall Road and toy trains climbing through pine forests.",
    heroImage: ss("Udaipur Rajasthan India lake palace white"),
    bestTime: "March to June, December to February (snow)",
    highlights: [
      "Toy train to Kalka (UNESCO)",
      "The Ridge and Mall Road",
      "Jakhoo Temple above the town",
      "Kufri snow point",
    ],
    nearby: ["manali", "dharamshala"],
  },
  {
    slug: "dharamshala",
    name: "Dharamshala",
    state: "Himachal Pradesh",
    stateSlug: "himachal-pradesh",
    category: "Spiritual",
    tagline: "Home of the Dalai Lama",
    description:
      "Tibetan exile culture, mountain monasteries and the calm of McLeod Ganj — Dharamshala is the Himalaya's spiritual crossroads.",
    heroImage: ss("Delhi India Red Fort gate heritage"),
    bestTime: "March to June, October to December",
    highlights: [
      "Kangra Valley views from Bhagsu",
      "Tsuglagkhang temple complex",
      "Triund trek overnight",
      "Tibetan food and craft market",
    ],
    nearby: ["shimla", "rishikesh"],
  },
  {
    slug: "rishikesh",
    name: "Rishikesh",
    state: "Uttarakhand",
    stateSlug: "uttarakhand",
    category: "Adventure",
    tagline: "Yoga town on the Ganges",
    description:
      "The world's yoga capital and India's rafting capital in one — Rishikesh is where seekers and adrenaline junkies share the same river.",
    heroImage: ss("Gangtok Sikkim India mountains monastery"),
    bestTime: "September to June",
    highlights: [
      "White-water rafting on the Ganges",
      "Lakshman Jhula and evening aarti",
      "Yoga and meditation retreats",
      "Camping by the river",
    ],
    nearby: ["haridwar", "manali"],
  },
  {
    slug: "haridwar",
    name: "Haridwar",
    state: "Uttarakhand",
    stateSlug: "uttarakhand",
    category: "Spiritual",
    tagline: "Gateway to the gods",
    description:
      "Where the Ganges leaves the mountains — Haridwar's evening aarti sets a thousand lamps adrift on the holy river.",
    heroImage: ss("Varanasi India Ganges ghats temple"),
    bestTime: "October to March",
    highlights: [
      "Har Ki Pauri Ganga Aarti",
      "Kumbh Mela years (every 12)",
      "Mansa Devi cable car",
      "Ayurvedic and wellness stays",
    ],
    nearby: ["rishikesh", "nainital"],
  },
  {
    slug: "nainital",
    name: "Nainital",
    state: "Uttarakhand",
    stateSlug: "uttarakhand",
    category: "Nature",
    tagline: "The lake in the hills",
    description:
      "A pear-shaped emerald lake ringed by forested peaks — Nainital is the Kumaon hills' classic lake resort.",
    heroImage: ss("Srinagar Kashmir India Dal Lake shikara"),
    bestTime: "March to June, October to February (snow)",
    highlights: [
      "Boating on Naini Lake",
      "Snow View Point by cable car",
      "Naina Devi Temple",
      "Walk the Mall Road at dusk",
    ],
    nearby: ["haridwar", "rishikesh"],
  },
  {
    slug: "amritsar",
    name: "Amritsar",
    state: "Punjab",
    stateSlug: "punjab",
    category: "Spiritual",
    tagline: "The golden temple's city",
    description:
      "The Harmandir Sahib glows gold over its sacred pool, and the Wagah border ceremony erupts each evening — Amritsar is Punjab's radiant heart.",
    heroImage: ss("Amritsar Punjab India Golden Temple"),
    bestTime: "October to March",
    highlights: [
      "Golden Temple at sunrise",
      "Langar, the world's largest free kitchen",
      "Wagah border ceremony at sunset",
      "Amritsari kulcha breakfast trail",
    ],
    nearby: ["chandigarh", "delhi"],
  },
  {
    slug: "chandigarh",
    name: "Chandigarh",
    state: "Chandigarh",
    stateSlug: "chandigarh",
    category: "Culture",
    tagline: "The city beautiful",
    description:
      "Le Corbusier's planned city of boulevards, the Rock Garden's folk-art fantasy, and lakeside evenings — India's most designed metropolis.",
    heroImage: ss("Chandigarh India Rock Garden city"),
    bestTime: "October to March",
    highlights: [
      "Rock Garden's recycled sculptures",
      "Sukhna Lake promenade",
      "Capitol Complex (UNESCO)",
      "Sector 17 food and shopping",
    ],
    nearby: ["amritsar", "shimla"],
  },
  {
    slug: "kutch",
    name: "Rann of Kutch",
    state: "Gujarat",
    stateSlug: "gujarat",
    category: "Desert",
    tagline: "The white desert",
    description:
      "An endless salt flat that turns silver under the full moon — the Rann is Gujarat's surreal, shimmering otherworld.",
    heroImage: ss("Pushkar Rajasthan India camel fair lake"),
    bestTime: "November to February",
    highlights: [
      "Full-moon nights on the white desert",
      "Rann Utsav cultural festival",
      "Bhuj's crafts and embroidery villages",
      "Flamingo sanctuary at Kala Dungar",
    ],
    nearby: ["dwarka", "gir"],
  },
  {
    slug: "dwarka",
    name: "Dwarka",
    state: "Gujarat",
    stateSlug: "gujarat",
    category: "Spiritual",
    tagline: "Krishna's ancient city",
    description:
      "One of the four holiest Char Dham sites, where legend places Krishna's capital — Dwarka sits where the desert meets the sea.",
    heroImage: ss("Dwarka Gujarat India temple coast"),
    bestTime: "November to February",
    highlights: [
      "Dwarkadhish Temple's towering shikhara",
      "Bet Dwarka island crossing",
      "Sunset at Dwarka beach",
      "Nageshwar Jyotirlinga",
    ],
    nearby: ["kutch", "gir"],
  },
  {
    slug: "gir",
    name: "Gir National Park",
    state: "Gujarat",
    stateSlug: "gujarat",
    category: "Wildlife",
    tagline: "Home of the Asiatic lion",
    description:
      "The only place on earth where Asiatic lions roam wild — Gir's teak forests hold India's most exclusive safari.",
    heroImage: ss("Gir National Park Gujarat India lion wildlife"),
    bestTime: "December to March",
    highlights: [
      "Lion safari at dawn",
      "Devalia safari park",
      "Kamleshwar Dam birding",
      "Somnath temple nearby",
    ],
    nearby: ["dwarka", "kutch"],
  },
  {
    slug: "ajanta-ellora",
    name: "Ajanta & Ellora",
    state: "Maharashtra",
    stateSlug: "maharashtra",
    category: "Heritage",
    tagline: "Temples carved from mountains",
    description:
      "Monasteries, shrines and the great Kailasa — two UNESCO cave complexes carved by hand into the Deccan rock over centuries.",
    heroImage: ss("Mumbai India Marine Drive city skyline"),
    bestTime: "November to February",
    highlights: [
      "Kailasa Temple, carved top-down",
      "Ajanta's frescoes and viharas",
      "Ellora's Hindu, Jain and Buddhist caves",
      "Bibika Maqbara en route",
    ],
    nearby: ["mumbai", "lonavala"],
  },
  {
    slug: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    stateSlug: "maharashtra",
    category: "Culture",
    tagline: "The city that never sleeps",
    description:
      "Bollywood, dabbawalas, colonial arches and monsoon beaches — Mumbai is India's most alive city, powered by pure momentum.",
    heroImage: ss("Mumbai India Marine Drive city skyline"),
    bestTime: "November to February",
    highlights: [
      "Marine Drive at night",
      "Gateway of India and Elephanta Caves",
      "Dharavi and the old mills",
      "Street food crawl from Vada Pav to Misal",
    ],
    nearby: ["ajanta-ellora", "lonavala"],
  },
  {
    slug: "lonavala",
    name: "Lonavala",
    state: "Maharashtra",
    stateSlug: "maharashtra",
    category: "Nature",
    tagline: "Monsoon hills of the ghats",
    description:
      "Misty valleys, forts and waterfalls along the Western Ghats — Lonavala is Mumbai's green escape and chikki capital.",
    heroImage: ss("Lonavala Maharashtra India monsoon hills"),
    bestTime: "June to September (monsoon), November to February",
    highlights: [
      "Tiger Point and sunset views",
      "Rajmachi and Lohagad forts",
      "Bhushi Dam waterfalls",
      "Karla and Bhaja caves",
    ],
    nearby: ["mumbai", "ajanta-ellora"],
  },
  {
    slug: "goa",
    name: "Goa",
    state: "Goa",
    stateSlug: "goa",
    category: "Beaches",
    tagline: "Sun, sand and slow living",
    description:
      "Portuguese churches, beach shacks and rivers of palm — Goa is India's original holiday state, north loud and south serene.",
    heroImage: ss("Dwarka Gujarat India temple coast"),
    bestTime: "November to March",
    highlights: [
      "Palolem and Agonda in the south",
      "Old Goa's basilicas",
      "Spice plantation tours",
      "Sunset cruise on the Mandovi",
    ],
    nearby: ["coorg", "hampi"],
  },
  {
    slug: "hampi",
    name: "Hampi",
    state: "Karnataka",
    stateSlug: "karnataka",
    category: "Heritage",
    tagline: "Ruins of the Vijayanagara empire",
    description:
      "Boulders, temples and the remains of a medieval superpower — Hampi is a UNESCO open-air museum unlike any other on earth.",
    heroImage: ss("Hampi Karnataka India ruins boulders temple"),
    bestTime: "November to February",
    highlights: [
      "Virupaksha Temple at dawn",
      "Sunset from Matanga Hill",
      "Coracle ride on the Tungabhadra",
      "Hire benakal and the royal enclosure",
    ],
    nearby: ["mysuru", "coorg"],
  },
  {
    slug: "mysuru",
    name: "Mysuru",
    state: "Karnataka",
    stateSlug: "karnataka",
    category: "Heritage",
    tagline: "City of palaces",
    description:
      "The Amba Vilas Palace in all its illuminated glory — Mysuru is Karnataka's royal city, famous for Dasara and silk.",
    heroImage: ss("Hampi Karnataka India ruins boulders temple"),
    bestTime: "September to March",
    highlights: [
      "Mysore Palace light-up at dusk",
      "Chamundi Hill temple",
      "Mysuru Dasara (October)",
      "Silk weaving and sandalwood craft",
    ],
    nearby: ["hampi", "coorg"],
  },
  {
    slug: "coorg",
    name: "Coorg",
    state: "Karnataka",
    stateSlug: "karnataka",
    category: "Nature",
    tagline: "Scotland of India",
    description:
      "Misty coffee estates, waterfalls and Kodava hospitality — Coorg is the Western Ghats' greenest, most aromatic district.",
    heroImage: ss("Coorg Karnataka India coffee estate mist"),
    bestTime: "October to March",
    highlights: [
      "Coffee plantation walks",
      "Abbey and Irupu falls",
      "Madikeri Fort and Raja's Seat",
      "Dubare elephant camp",
    ],
    nearby: ["mysuru", "hampi"],
  },
  {
    slug: "bengaluru",
    name: "Bengaluru",
    state: "Karnataka",
    stateSlug: "karnataka",
    category: "Culture",
    tagline: "Garden city of India",
    description:
      "Tech capital by day, garden city and craft-beer town by night — Bengaluru is India's most cosmopolitan southern city.",
    heroImage: ss("Bengaluru Karnataka India city garden"),
    bestTime: "October to March",
    highlights: [
      "Lalbagh and Cubbon Park mornings",
      "Tipu Sultan's Summer Palace",
      "Nandi Hills sunrise",
      "Koramangala and Indiranagar cafés",
    ],
    nearby: ["coorg", "mysuru"],
  },
  {
    slug: "alleppey",
    name: "Alleppey",
    state: "Kerala",
    stateSlug: "kerala",
    category: "Nature",
    tagline: "Venice of the East",
    description:
      "Houseboats drift through palm-lined backwaters — Alleppey is Kerala's most iconic, most serene experience.",
    heroImage: ss("Alleppey Kerala India backwaters houseboat"),
    bestTime: "September to March",
    highlights: [
      "Overnight houseboat on the backwaters",
      "Vembanad Lake at sunrise",
      "Kerala sadya (feast) lunch",
      "Alappuzha beach and lighthouse",
    ],
    nearby: ["kochi", "munnar"],
  },
  {
    slug: "munnar",
    name: "Munnar",
    state: "Kerala",
    stateSlug: "kerala",
    category: "Nature",
    tagline: "Tea gardens in the clouds",
    description:
      "Rolling tea estates at 6,000 feet, wildflowers and mist — Munnar is Kerala's cool, green highlands.",
    heroImage: ss("Coorg Karnataka India coffee estate mist"),
    bestTime: "September to March",
    highlights: [
      "Tea museum and estate tours",
      "Eravikulam National Park and nilgiri tahr",
      "Attukal and Lakkam waterfalls",
      "Top Station viewpoint",
    ],
    nearby: ["alleppey", "kochi"],
  },
  {
    slug: "kochi",
    name: "Kochi",
    state: "Kerala",
    stateSlug: "kerala",
    category: "Culture",
    tagline: "Queen of the Arabian Sea",
    description:
      "Chinese fishing nets, Dutch houses and synagogues — Kochi is Kerala's trading-history port, layered with the world.",
    heroImage: ss("Coorg Karnataka India coffee estate mist"),
    bestTime: "October to March",
    highlights: [
      "Fort Kochi's Chinese fishing nets",
      "Mattancherry Palace and Jew Town",
      "Kathakali performance",
      "Backwater day cruise",
    ],
    nearby: ["alleppey", "munnar"],
  },
  {
    slug: "trivandrum",
    name: "Thiruvananthapuram",
    state: "Kerala",
    stateSlug: "kerala",
    category: "Beaches",
    tagline: "Kerala's southern capital",
    description:
      "Temple city by day, palm beaches by evening — Trivandrum is where Kerala's culture meets its best coastline.",
    heroImage: ss("Trivandrum Kerala India beach Kovalam"),
    bestTime: "September to March",
    highlights: [
      "Padmanabhaswamy Temple",
      "Varkala cliff beach nearby",
      "Kovalam lighthouse beach",
      "Napier Museum's art",
    ],
    nearby: ["kanyakumari", "alleppey"],
  },
  {
    slug: "madurai",
    name: "Madurai",
    state: "Tamil Nadu",
    stateSlug: "tamil-nadu",
    category: "Spiritual",
    tagline: "City of the Meenakshi temple",
    description:
      "Fourteen gopurams painted with a million gods — Madurai's temple is southern India's most spectacular sacred complex.",
    heroImage: ss("Bengaluru Karnataka India city garden"),
    bestTime: "October to March",
    highlights: [
      "Meenakshi Amman Temple at night",
      "Temple tour with a local guide",
      "Palace of Thirumalai Nayakkar",
      "Jigarthanda and idli breakfasts",
    ],
    nearby: ["kanyakumari", "mahabalipuram"],
  },
  {
    slug: "mahabalipuram",
    name: "Mahabalipuram",
    state: "Tamil Nadu",
    stateSlug: "tamil-nadu",
    category: "Heritage",
    tagline: "Shore temple by the sea",
    description:
      "Rock-cut rathas and a temple that has faced the Bay of Bengal for 1,300 years — Mahabalipuram is Pallava stone at its finest.",
    heroImage: ss("Bengaluru Karnataka India city garden"),
    bestTime: "November to February",
    highlights: [
      "Shore Temple at sunrise",
      "Descent of the Ganges bas-relief",
      "Five Rathas monuments",
      "Crocodile Bank nearby",
    ],
    nearby: ["madurai", "kanyakumari"],
  },
  {
    slug: "kanyakumari",
    name: "Kanyakumari",
    state: "Tamil Nadu",
    stateSlug: "tamil-nadu",
    category: "Beaches",
    tagline: "Where three seas meet",
    description:
      "The southernmost tip of India — sunrise over the meeting of the Arabian Sea, Bay of Bengal and Indian Ocean.",
    heroImage: ss("Kanyakumari Tamil Nadu India three seas sunrise"),
    bestTime: "October to March",
    highlights: [
      "Sunrise at Vivekananda Rock",
      "Thiruvalluvar statue",
      "Kumari Amman temple",
      "Padmanabhapuram palace nearby",
    ],
    nearby: ["trivandrum", "madurai"],
  },
  {
    slug: "ooty",
    name: "Ooty",
    state: "Tamil Nadu",
    stateSlug: "tamil-nadu",
    category: "Nature",
    tagline: "Queen of the Nilgiris",
    description:
      "Tea slopes, toy trains and botanic gardens at 7,000 feet — Ooty is the south's classic hill station.",
    heroImage: ss("Coorg Karnataka India coffee estate mist"),
    bestTime: "March to June, September to November",
    highlights: [
      "Nilgiri toy train",
      "Botanical Gardens",
      "Doddabetta peak sunrise",
      "Tea factory tours",
    ],
    nearby: ["kanyakumari", "madurai"],
  },
  {
    slug: "hyderabad",
    name: "Hyderabad",
    state: "Telangana",
    stateSlug: "telangana",
    category: "Heritage",
    tagline: "City of pearls and biryani",
    description:
      "Golconda's acoustic wonder, the Charminar's bazaars and a food culture that needs no defence — Hyderabad is Deccan grandeur.",
    heroImage: ss("Chandigarh India Rock Garden city"),
    bestTime: "October to March",
    highlights: [
      "Charminar and Laad Bazaar",
      "Golconda Fort sound & light show",
      "Hyderabadi biryani pilgrimage",
      "Ramoji Film City",
    ],
    nearby: ["mahabalipuram", "hampi"],
  },
  {
    slug: "tirupati",
    name: "Tirupati",
    state: "Andhra Pradesh",
    stateSlug: "andhra-pradesh",
    category: "Spiritual",
    tagline: "The hill of Lord Venkateswara",
    description:
      "One of the world's most visited pilgrimage sites — Tirupati's seven hills draw millions of devotees each year.",
    heroImage: ss("Bengaluru Karnataka India city garden"),
    bestTime: "October to March",
    highlights: [
      "Tirumala darshan",
      "Sri Vari Museum",
      "Akasa Ganga falls",
      "Sila Thoranam and deer park",
    ],
    nearby: ["visakhapatnam", "hyderabad"],
  },
  {
    slug: "visakhapatnam",
    name: "Visakhapatnam",
    state: "Andhra Pradesh",
    stateSlug: "andhra-pradesh",
    category: "Beaches",
    tagline: "City of destiny",
    description:
      "Araku Valley's coffee hills, the Bay of Bengal's long beaches and the ancient Buddhist site of Borra — Vizag has it all.",
    heroImage: ss("Srinagar Kashmir India Dal Lake shikara"),
    bestTime: "October to March",
    highlights: [
      "Araku Valley toy train",
      "Borra Caves",
      "Rushikonda beach",
      "Submarine museum",
    ],
    nearby: ["tirupati"],
  },
  {
    slug: "khajuraho",
    name: "Khajuraho",
    state: "Madhya Pradesh",
    stateSlug: "madhya-pradesh",
    category: "Heritage",
    tagline: "Temples of celestial love",
    description:
      "Carved sandstone temples where divine and human passion meet in stone — Khajuraho is India's most sensuous UNESCO site.",
    heroImage: ss("Hampi Karnataka India ruins boulders temple"),
    bestTime: "October to March",
    highlights: [
      "Western group of temples at sunrise",
      "Sound & light show",
      "Khajuraho Dance Festival (February)",
      "Panna tiger reserve nearby",
    ],
    nearby: ["orchha", "kanha"],
  },
  {
    slug: "orchha",
    name: "Orchha",
    state: "Madhya Pradesh",
    stateSlug: "madhya-pradesh",
    category: "Heritage",
    tagline: "A royal town frozen in time",
    description:
      "Chhatris on the Betwa river and palaces that time forgot — Orchha is Bundela grandeur in a quiet river town.",
    heroImage: ss("Orchha Madhya Pradesh India palace river chhatris"),
    bestTime: "October to March",
    highlights: [
      "Jahangir Mahal",
      "Chhatris at sunset",
      "Ram Raja temple",
      "River-side walks and camping",
    ],
    nearby: ["khajuraho", "kanha"],
  },
  {
    slug: "kanha",
    name: "Kanha National Park",
    state: "Madhya Pradesh",
    stateSlug: "madhya-pradesh",
    category: "Wildlife",
    tagline: "The land of the tiger",
    description:
      "The inspiration for Kipling's Jungle Book — Kanha's sal forests hold one of India's best tiger populations.",
    heroImage: ss("Gir National Park Gujarat India lion wildlife"),
    bestTime: "October to June",
    highlights: [
      "Tiger safaris at dawn",
      "Kanha meadows and barasingha",
      "Bamni Dadar sunset point",
      "Tribal museum of the Baiga people",
    ],
    nearby: ["khajuraho", "orchha"],
  },
  {
    slug: "bodh-gaya",
    name: "Bodh Gaya",
    state: "Bihar",
    stateSlug: "bihar",
    category: "Spiritual",
    tagline: "Where the Buddha woke up",
    description:
      "Under the Bodhi tree, Siddhartha became the Buddha — Bodh Gaya is Buddhism's most sacred pilgrimage site.",
    heroImage: ss("Bodh Gaya Bihar India Mahabodhi temple"),
    bestTime: "October to March",
    highlights: [
      "Mahabodhi Temple complex",
      "Meditation at the Bodhi tree",
      "Great Buddha statue",
      "Monasteries of many nations",
    ],
    nearby: ["nalanda", "varanasi"],
  },
  {
    slug: "nalanda",
    name: "Nalanda",
    state: "Bihar",
    stateSlug: "bihar",
    category: "Heritage",
    tagline: "The world's first university",
    description:
      "A 5th-century monastic university that taught the world — Nalanda's red-brick ruins still inspire awe.",
    heroImage: ss("Nalanda Bihar India ruins university"),
    bestTime: "October to March",
    highlights: [
      "Nalanda ruins and museum",
      "Archaeological survey walk",
      "Nalanda Multimedia Museum",
      "Rajgir hills nearby",
    ],
    nearby: ["bodh-gaya", "varanasi"],
  },
  {
    slug: "darjeeling",
    name: "Darjeeling",
    state: "West Bengal",
    stateSlug: "west-bengal",
    category: "Mountains",
    tagline: "Queen of the hills",
    description:
      "Kanchenjunga at dawn, toy trains and the world's most famous tea — Darjeeling is the Himalaya's most romantic hill station.",
    heroImage: ss("Darjeeling West Bengal India tea garden Kanchenjunga"),
    bestTime: "March to May, October to December",
    highlights: [
      "Tiger Hill sunrise over Kanchenjunga",
      "Darjeeling Himalayan Railway",
      "Tea estate tastings",
      "Batasia Loop and Peace Pagoda",
    ],
    nearby: ["gangtok", "kolkata"],
  },
  {
    slug: "gangtok",
    name: "Gangtok",
    state: "Sikkim",
    stateSlug: "sikkim",
    category: "Mountains",
    tagline: "Capital in the clouds",
    description:
      "Nathula passes, monasteries and prayer flags — Gangtok is the gateway to Sikkim's clean, calm Himalaya.",
    heroImage: ss("Gulmarg Kashmir India meadow mountains snow"),
    bestTime: "March to May, October to December",
    highlights: [
      "Tsomgo Lake and Nathula pass",
      "Rumtek Monastery",
      "MG Marg evening stroll",
      "Himalayan Zoological Park",
    ],
    nearby: ["darjeeling", "pelling"],
  },
  {
    slug: "pelling",
    name: "Pelling",
    state: "Sikkim",
    stateSlug: "sikkim",
    category: "Mountains",
    tagline: "Facing Kanchenjunga",
    description:
      "The closest you can stand to Kanchenjunga's massif — Pelling is quiet Sikkim with the world's best mountain view.",
    heroImage: ss("Gulmarg Kashmir India meadow mountains snow"),
    bestTime: "October to May",
    highlights: [
      "Kanchenjunga sunrise from Khecheopalri",
      "Pemayangtse Monastery",
      "Sangachoeling monastery trek",
      "Rabdentse ruins",
    ],
    nearby: ["gangtok", "darjeeling"],
  },
  {
    slug: "shillong",
    name: "Shillong",
    state: "Meghalaya",
    stateSlug: "meghalaya",
    category: "Culture",
    tagline: "Scotland of the East",
    description:
      "Waterfalls, pine hills and a music scene that never stops — Shillong is the Northeast's most spirited hill capital.",
    heroImage: ss("Gangtok Sikkim India mountains monastery"),
    bestTime: "October to May",
    highlights: [
      "Umiam Lake",
      "Laitlum Canyon viewpoint",
      "Elephant Falls",
      "Don Bosco museum of cultures",
    ],
    nearby: ["cherrapunji", "mawsynram"],
  },
  {
    slug: "cherrapunji",
    name: "Cherrapunji",
    state: "Meghalaya",
    stateSlug: "meghalaya",
    category: "Nature",
    tagline: "The wettest place on earth",
    description:
      "Rainforest canyons, living root bridges and mists that roll like tides — Cherrapunji redefined what wet means.",
    heroImage: ss("Cherrapunji Meghalaya India waterfall living root"),
    bestTime: "October to May",
    highlights: [
      "Nohkalikai Falls",
      "Living root bridge trek",
      "Mawsmai caves",
      "Double decker root bridge",
    ],
    nearby: ["shillong", "mawsynram"],
  },
  {
    slug: "mawsynram",
    name: "Mawsynram",
    state: "Meghalaya",
    stateSlug: "meghalaya",
    category: "Nature",
    tagline: "The rainiest place on earth",
    description:
      "The village that receives more rain than anywhere else — Mawsynram is a world of waterfalls and living roots.",
    heroImage: ss("Lonavala Maharashtra India monsoon hills"),
    bestTime: "October to May",
    highlights: [
      "Mawjymbuin caves",
      "Living root bridges",
      "Waterfall viewpoints",
      "Mossy forest walks",
    ],
    nearby: ["cherrapunji", "shillong"],
  },
  {
    slug: "kaziranga",
    name: "Kaziranga",
    state: "Assam",
    stateSlug: "assam",
    category: "Wildlife",
    tagline: "Land of the one-horned rhino",
    description:
      "Two-thirds of the world's one-horned rhinos graze Kaziranga's grasslands — the finest wildlife park in India.",
    heroImage: ss("Gir National Park Gujarat India lion wildlife"),
    bestTime: "November to April",
    highlights: [
      "Elephant safari at dawn",
      "Jeep safari in the central range",
      "Rhino and tiger sightings",
      "Brahmaputra river sunset",
    ],
    nearby: ["guwahati", "shillong"],
  },
  {
    slug: "guwahati",
    name: "Guwahati",
    state: "Assam",
    stateSlug: "assam",
    category: "Culture",
    tagline: "Gateway to the Northeast",
    description:
      "Kamakhya's temple hill and Brahmaputra cruises — Guwahati is where the Northeast journey begins.",
    heroImage: ss("Nalanda Bihar India ruins university"),
    bestTime: "November to March",
    highlights: [
      "Kamakhya Temple",
      "Sunset cruise on the Brahmaputra",
      "Umananda island temple",
      "Assam silk and craft shopping",
    ],
    nearby: ["kaziranga", "shillong"],
  },
  {
    slug: "tawang",
    name: "Tawang",
    state: "Arunachal Pradesh",
    stateSlug: "arunachal-pradesh",
    category: "Mountains",
    tagline: "The dawn-lit monastery",
    description:
      "India's largest monastery, mountain passes and the borderland of the eastern Himalaya — Tawang is remote in the best way.",
    heroImage: ss("Gulmarg Kashmir India meadow mountains snow"),
    bestTime: "October to April",
    highlights: [
      "Tawang Monastery at dawn",
      "Sela Pass at 13,700 feet",
      "Madhuri Lake",
      "Bumla pass border post",
    ],
    nearby: ["dzuko", "kohima"],
  },
  {
    slug: "kohima",
    name: "Kohima",
    state: "Nagaland",
    stateSlug: "nagaland",
    category: "Culture",
    tagline: "Land of the Angami warriors",
    description:
      "The WWII battlefield of Kohima and living Naga culture — Kohima is the Northeast's most storied hill capital.",
    heroImage: ss("Gangtok Sikkim India mountains monastery"),
    bestTime: "November to April",
    highlights: [
      "Kohima War Cemetery",
      "Naga Heritage Village",
      "Hornbill Festival (December)",
      "Khonoma green village",
    ],
    nearby: ["dzuko", "tawang"],
  },
  {
    slug: "dzuko",
    name: "Dzüko Valley",
    state: "Nagaland",
    stateSlug: "nagaland",
    category: "Adventure",
    tagline: "The valley of flowers of the east",
    description:
      "A flower-filled high valley shared by Nagaland and Manipur — Dzüko is the Northeast's great trek.",
    heroImage: ss("Lonavala Maharashtra India monsoon hills"),
    bestTime: "June to October",
    highlights: [
      "Dzükou trek (3–4 days)",
      "Rhododendron season (April–June)",
      "Camping in the valley",
      "Viswema village hospitality",
    ],
    nearby: ["kohima", "loktak"],
  },
  {
    slug: "loktak",
    name: "Loktak Lake",
    state: "Manipur",
    stateSlug: "manipur",
    category: "Nature",
    tagline: "The floating islands",
    description:
      "The only floating national park on earth — Loktak's phumdis drift with the world's last sangai deer.",
    heroImage: ss("Manipur India Loktak Lake floating islands"),
    bestTime: "October to March",
    highlights: [
      "Keibul Lamjao floating park",
      "Phumdi houseboat stays",
      "Sendra island viewpoint",
      "Thanga village fishing life",
    ],
    nearby: ["aizawl", "dzuko"],
  },
  {
    slug: "aizawl",
    name: "Aizawl",
    state: "Mizoram",
    stateSlug: "mizoram",
    category: "Culture",
    tagline: "City in the blue mountains",
    description:
      "Ridges of red-roofed homes above green valleys — Aizawl is Mizoram's clean, musical capital.",
    heroImage: ss("Gangtok Sikkim India mountains monastery"),
    bestTime: "November to March",
    highlights: [
      "Durtlang hills viewpoint",
      "Reiek Tlang trek",
      "Mizoram State Museum",
      "Sunday choral music",
    ],
    nearby: ["loktak", "agartala"],
  },
  {
    slug: "agartala",
    name: "Agartala",
    state: "Tripura",
    stateSlug: "tripura",
    category: "Heritage",
    tagline: "Palace city of the east",
    description:
      "The Ujjayanta Palace and royal temples — Agartala is Tripura's quiet, historic capital.",
    heroImage: ss("Chandigarh India Rock Garden city"),
    bestTime: "October to March",
    highlights: [
      "Ujjayanta Palace",
      "Neermahal lake palace",
      "Chaturdash Devta temple",
      "Sepahijala wildlife sanctuary",
    ],
    nearby: ["aizawl"],
  },
  {
    slug: "konark",
    name: "Konark",
    state: "Odisha",
    stateSlug: "odisha",
    category: "Heritage",
    tagline: "The sun temple's chariot",
    description:
      "A 13th-century temple built as the sun god's chariot — Konark's carved wheels have turned for 800 years.",
    heroImage: ss("Nalanda Bihar India ruins university"),
    bestTime: "November to February",
    highlights: [
      "Sun Temple at sunrise",
      "Konark Dance Festival (December)",
      "Chandrabhaga beach",
      "Raghurajpur pattachitra village",
    ],
    nearby: ["puri"],
  },
  {
    slug: "puri",
    name: "Puri",
    state: "Odisha",
    stateSlug: "odisha",
    category: "Spiritual",
    tagline: "Jagannath's seaside town",
    description:
      "The Jagannath Temple and long golden beaches — Puri is Odisha's holiest and most laid-back town.",
    heroImage: ss("Gangtok Sikkim India mountains monastery"),
    bestTime: "November to February",
    highlights: [
      "Jagannath Temple darshan",
      "Puri beach sunrise",
      "Rath Yatra (June–July)",
      "Sea food and chhena poda",
    ],
    nearby: ["konark"],
  },
  {
    slug: "chitrakote",
    name: "Chitrakote Falls",
    state: "Chhattisgarh",
    stateSlug: "chhattisgarh",
    category: "Nature",
    tagline: "Niagara of India",
    description:
      "India's widest waterfall, horseshoe-shaped across the Indravati river — Chitrakote is the tribal heart's grand spectacle.",
    heroImage: ss("Cherrapunji Meghalaya India waterfall living root"),
    bestTime: "July to October (monsoon), November to February",
    highlights: [
      "Monsoon flow at full power",
      "Boat ride near the falls",
      "Tirathgarh waterfalls",
      "Kanger Valley caves",
    ],
    nearby: ["ranki"],
  },
  {
    slug: "ranki",
    name: "Ranchi & Hundru Falls",
    state: "Jharkhand",
    stateSlug: "jharkhand",
    category: "Nature",
    tagline: "The falls of Chota Nagpur",
    description:
      "Hundru's 98-metre drop and the plateau forests of Jharkhand — Ranchi is eastern India's green weekend.",
    heroImage: ss("Gangtok Sikkim India mountains monastery"),
    bestTime: "October to March",
    highlights: [
      "Hundru Falls",
      "Dassam Falls",
      "Jonha Falls viewpoint",
      "Tagore Hill sunset",
    ],
    nearby: ["chitrakote"],
  },
  {
    slug: "kolkata",
    name: "Kolkata",
    state: "West Bengal",
    stateSlug: "west-bengal",
    category: "Culture",
    tagline: "The city of joy",
    description:
      "Victorian avenues, tram lines, adda and the world's best street food — Kolkata is India's most soulful metropolis.",
    heroImage: ss("Chandigarh India Rock Garden city"),
    bestTime: "October to March",
    highlights: [
      "Victoria Memorial at sunset",
      "Howrah Bridge crossing",
      "College Street book market",
      "Kathi roll and mishti trail",
    ],
    nearby: ["darjeeling", "sundarbans"],
  },
  {
    slug: "sundarbans",
    name: "Sundarbans",
    state: "West Bengal",
    stateSlug: "west-bengal",
    category: "Wildlife",
    tagline: "Realm of the royal Bengal tiger",
    description:
      "The world's largest mangrove delta, where tigers swim between islands — the Sundarbans is India's wildest river country.",
    heroImage: ss("Cherrapunji Meghalaya India waterfall living root"),
    bestTime: "November to February",
    highlights: [
      "Sundarbans tiger cruise",
      "Sajnekhali watchtower",
      "Dobanki canopy walk",
      "Crocodile and dolphin spotting",
    ],
    nearby: ["kolkata"],
  },
  {
    slug: "andaman",
    name: "Andaman Islands",
    state: "Andaman & Nicobar",
    stateSlug: "andaman-nicobar",
    category: "Beaches",
    tagline: "Emerald seas and rainforest",
    description:
      "Coral reefs, limestone caves and some of Asia's best beaches — the Andamans are India's island escape.",
    heroImage: ss("Kanyakumari Tamil Nadu India three seas sunrise"),
    bestTime: "November to May",
    highlights: [
      "Radhanagar Beach, Havelock",
      "Scuba diving and snorkelling",
      "Cellular Jail light & sound show",
      "Ross Island ruins",
    ],
    nearby: ["lakshadweep"],
  },
  {
    slug: "lakshadweep",
    name: "Lakshadweep",
    state: "Lakshadweep",
    stateSlug: "lakshadweep",
    category: "Beaches",
    tagline: "Coral atolls of the Arabian Sea",
    description:
      "Uncrowded lagoons and reefs in technicolour — Lakshadweep is India's most exclusive island chain.",
    heroImage: ss("Kanyakumari Tamil Nadu India three seas sunrise"),
    bestTime: "October to April",
    highlights: [
      "Agatti island lagoon",
      "Kadmat coral reef snorkelling",
      "Bangaram island stay",
      "Kayaking the calm lagoons",
    ],
    nearby: ["andaman"],
  },
  {
    slug: "puducherry",
    name: "Puducherry",
    state: "Puducherry",
    stateSlug: "puducherry",
    category: "Culture",
    tagline: "The French quarter by the sea",
    description:
      "Pastel villas, a boulevard café and the Sri Aurobindo Ashram — Puducherry is India's gentlest colonial town.",
    heroImage: ss("Chandigarh India Rock Garden city"),
    bestTime: "October to March",
    highlights: [
      "White Town promenade",
      "Sri Aurobindo Ashram",
      "Auroville's Matrimandir",
      "Auro Beach and cafés",
    ],
    nearby: ["mahabalipuram", "madurai"],
  },
  {
    slug: "auroville",
    name: "Auroville",
    state: "Puducherry",
    stateSlug: "puducherry",
    category: "Culture",
    tagline: "The city of dawn",
    description:
      "An international township built around a golden sphere — Auroville is an experiment in human unity.",
    heroImage: ss("Chandigarh India Rock Garden city"),
    bestTime: "October to March",
    highlights: [
      "Matrimandir viewpoint",
      "Auroville visitor centre",
      "Solar kitchen",
      "Botanical gardens",
    ],
    nearby: ["puducherry"],
  },
  {
    slug: "daman",
    name: "Daman",
    state: "Dadra & Nagar Haveli and Daman & Diu",
    stateSlug: "daman-diu",
    category: "Beaches",
    tagline: "The Portuguese coast",
    description:
      "Fort walls, fishing villages and quiet beaches — Daman is a small western coast made for slow weekends.",
    heroImage: ss("Trivandrum Kerala India beach Kovalam"),
    bestTime: "November to February",
    highlights: [
      "Daman Fort",
      "Devka and Jampore beaches",
      "Portuguese churches",
      "Mirasol lake garden",
    ],
    nearby: ["diu"],
  },
  {
    slug: "diu",
    name: "Diu",
    state: "Dadra & Nagar Haveli and Daman & Diu",
    stateSlug: "daman-diu",
    category: "Beaches",
    tagline: "An island of forts and palms",
    description:
      "A tiny Portuguese-era island with a great fort, calm beaches and cycling lanes — Diu is India's most relaxed coast.",
    heroImage: ss("Kanyakumari Tamil Nadu India three seas sunrise"),
    bestTime: "November to February",
    highlights: [
      "Diu Fort at sunset",
      "Naida and Nagoa beaches",
      "St. Paul's Church",
      "Cycle the island",
    ],
    nearby: ["daman"],
  },
  {
    slug: "gurugram",
    name: "Gurugram",
    state: "Haryana",
    stateSlug: "haryana",
    category: "Culture",
    tagline: "Millennium city",
    description:
      "The corporate capital beside Delhi — but also Sultanpur's bird lake and the heritage villages of the Aravalli foothills.",
    heroImage: ss("Orchha Madhya Pradesh India palace river chhatris"),
    bestTime: "October to March",
    highlights: [
      "Sultanpur National Park birding",
      "Leisure Valley and Cyber Hub",
      "Damdama lake",
      "Kingdom of Dreams",
    ],
    nearby: ["delhi", "chandigarh"],
  },
  {
    slug: "lucknow",
    name: "Lucknow",
    state: "Uttar Pradesh",
    stateSlug: "uttar-pradesh",
    category: "Culture",
    tagline: "City of nawabs and kebabs",
    description:
      "Nawabi architecture, refined etiquette and the most famous food in northern India — Lucknow is grace on the Gomti.",
    heroImage: ss("Orchha Madhya Pradesh India palace river chhatris"),
    bestTime: "October to March",
    highlights: [
      "Bara Imambara's labyrinth",
      "Chowk bazaars",
      "Tunday kabab trail",
      "Rumi Darwaza at night",
    ],
    nearby: ["agra", "varanasi"],
  },
  {
    slug: "allahabad",
    name: "Prayagraj",
    state: "Uttar Pradesh",
    stateSlug: "uttar-pradesh",
    category: "Spiritual",
    tagline: "Where the rivers meet",
    description:
      "The sangam of the Ganges, Yamuna and the mythical Saraswati — Prayagraj hosts the world's largest gathering of humanity.",
    heroImage: ss("Varanasi India Ganges ghats temple"),
    bestTime: "October to March",
    highlights: [
      "Sangam boat ride at dawn",
      "Kumbh Mela years (every 12)",
      "Anand Bhavan museum",
      "Allahabad Fort's Ashoka pillar",
    ],
    nearby: ["varanasi", "lucknow"],
  },
];

export const destinationsBySlug = new Map(
  destinations.map((d) => [d.slug, d]),
);

export const categories = [
  "Heritage",
  "Spiritual",
  "Beaches",
  "Mountains",
  "Wildlife",
  "Nature",
  "Adventure",
  "Culture",
  "Food",
  "Desert",
] as const;
