import type { Region, State } from "./types";
import { ss } from "./images";

export const states: State[] = [
  {
    id: "INRJ",
    name: "Rajasthan",
    slug: "rajasthan",
    kind: "State",
    region: "North",
    tagline: "The land of kings",
    description:
      "Fortresses rising from desert plains, blue cities and lake palaces — Rajasthan is India's grandest stage, where every citadel carries a dynasty and every courtyard a story.",
    heroImage: ss("Rajasthan India fort desert palace"),
    destinations: ["jaipur", "jodhpur", "udaipur", "jaisalmer", "pushkar"],
    experiences: ["heritage", "food", "culture"],
    bestTime: "October to March",
  },
  {
    id: "INJK",
    name: "Jammu & Kashmir",
    slug: "jammu-kashmir",
    kind: "Union Territory",
    region: "Himalayan",
    tagline: "Paradise on earth",
    description:
      "Shikaras gliding over Dal Lake, saffron fields, and the meadows of Gulmarg — Kashmir is the valley poets have spent centuries trying to describe.",
    heroImage: ss("Kashmir India mountains lake Dal"),
    destinations: ["srinagar", "gulmarg"],
    experiences: ["mountains", "nature"],
    bestTime: "April to October",
  },
  {
    id: "INLA",
    name: "Ladakh",
    slug: "ladakh",
    kind: "Union Territory",
    region: "Himalayan",
    tagline: "The land of high passes",
    description:
      "Moonscapes above 11,000 feet, turquoise lakes, and monasteries perched on cliffs — Ladakh is India's high-altitude desert, silent and enormous.",
    heroImage: ss("Ladakh India mountains landscape"),
    destinations: ["leh", "pangong"],
    experiences: ["adventure", "mountains", "spiritual"],
    bestTime: "May to September",
  },
  {
    id: "INHP",
    name: "Himachal Pradesh",
    slug: "himachal-pradesh",
    kind: "State",
    region: "Himalayan",
    tagline: "Land of the gods",
    description:
      "Pine forests, river valleys and Himalayan villages — Himachal moves from the bustle of Manali to the calm of Dharamshala without losing its mountain soul.",
    heroImage: ss("Ladakh India mountains landscape"),
    destinations: ["manali", "dharamshala", "shimla"],
    experiences: ["mountains", "adventure", "nature"],
    bestTime: "March to June, October to December",
  },
  {
    id: "INUT",
    name: "Uttarakhand",
    slug: "uttarakhand",
    kind: "State",
    region: "Himalayan",
    tagline: "The abode of gods",
    description:
      "Source of the Ganges, home to Char Dham pilgrimages and the yoga town of Rishikesh — Uttarakhand is where the mountains begin and the spirit goes quiet.",
    heroImage: ss("Uttarakhand India mountains waterfall"),
    destinations: ["rishikesh", "haridwar", "nainital"],
    experiences: ["adventure", "spiritual", "nature"],
    bestTime: "April to June, September to November",
  },
  {
    id: "INUP",
    name: "Uttar Pradesh",
    slug: "uttar-pradesh",
    kind: "State",
    region: "North",
    tagline: "The heartland of stories",
    description:
      "The Taj Mahal, the ghats of Varanasi, and the great plains of the Ganges — Uttar Pradesh holds more of India's iconic soul than almost anywhere else.",
    heroImage: ss("Taj Mahal Agra India"),
    destinations: ["agra", "varanasi", "lucknow"],
    experiences: ["heritage", "spiritual", "food"],
    bestTime: "October to March",
  },
  {
    id: "INPB",
    name: "Punjab",
    slug: "punjab",
    kind: "State",
    region: "North",
    tagline: "Land of five rivers",
    description:
      "Golden Temple radiance, mustard fields and hearty food — Punjab is warm, loud, and full of heart.",
    heroImage: ss("Golden Temple Amritsar India"),
    destinations: ["amritsar"],
    experiences: ["spiritual", "food", "culture"],
    bestTime: "October to March",
  },
  {
    id: "INHR",
    name: "Haryana",
    slug: "haryana",
    kind: "State",
    region: "North",
    tagline: "India's granary",
    description:
      "The fertile belt around Delhi — heritage villages, wetlands, and the corridor to the rest of northern India.",
    heroImage: ss("Gurugram Haryana India skyline"),
    destinations: ["gurugram"],
    experiences: ["culture", "food"],
    bestTime: "October to March",
  },
  {
    id: "INDL",
    name: "Delhi",
    slug: "delhi",
    kind: "Union Territory",
    region: "North",
    tagline: "A thousand years of empire",
    description:
      "Seven cities layered into one — Mughal monuments, colonial avenues and bazaars that never sleep. Delhi is India's relentless, magnificent heartbeat.",
    heroImage: ss("Delhi India Red Fort gate"),
    destinations: ["delhi"],
    experiences: ["heritage", "food", "culture"],
    bestTime: "October to March",
  },
  {
    id: "INGJ",
    name: "Gujarat",
    slug: "gujarat",
    kind: "State",
    region: "West",
    tagline: "The western gateway",
    description:
      "The white desert of Kutch, Asiatic lions at Gir, and the salt-trading history of the coast — Gujarat is a state of bold contrasts.",
    heroImage: ss("Rann of Kutch Gujarat India desert"),
    destinations: ["kutch", "dwarka", "gir"],
    experiences: ["wildlife", "culture", "food"],
    bestTime: "November to February",
  },
  {
    id: "INMH",
    name: "Maharashtra",
    slug: "maharashtra",
    kind: "State",
    region: "West",
    tagline: "Empires, coasts and monsoon hills",
    description:
      "From the cave temples of Ajanta-Ellora to the Western Ghats and the beating heart of Mumbai — Maharashtra is India in fast-forward.",
    heroImage: ss("Mumbai India skyline city"),
    destinations: ["ajanta-ellora", "mumbai", "lonavala"],
    experiences: ["heritage", "food", "nature"],
    bestTime: "November to February",
  },
  {
    id: "INGA",
    name: "Goa",
    slug: "goa",
    kind: "State",
    region: "West",
    tagline: "Where the sun sets slowly",
    description:
      "Portuguese churches, palm-lined beaches and river cruises — Goa is India's most unhurried state, made for doing nothing very well.",
    heroImage: ss("Goa India beach coast palm"),
    destinations: ["goa"],
    experiences: ["beaches", "food", "culture"],
    bestTime: "November to March",
  },
  {
    id: "INKA",
    name: "Karnataka",
    slug: "karnataka",
    kind: "State",
    region: "South",
    tagline: "Palaces, ruins and coffee hills",
    description:
      "Hampi's boulder-strewn ruins, Mysuru's palace, and the misty coffee estates of Coorg — Karnataka is the south's most varied canvas.",
    heroImage: ss("Karnataka India Mysore Palace"),
    destinations: ["hampi", "mysuru", "coorg", "bengaluru"],
    experiences: ["heritage", "nature", "food"],
    bestTime: "October to March",
  },
  {
    id: "INKL",
    name: "Kerala",
    slug: "kerala",
    kind: "State",
    region: "South",
    tagline: "God's own country",
    description:
      "Backwaters, spice hills and Ayurveda — Kerala is lush, slow, and deeply green, a tropical counterpoint to the rest of India.",
    heroImage: ss("Kerala India backwaters houseboat"),
    destinations: ["alleppey", "munnar", "kochi", "trivandrum"],
    experiences: ["nature", "food", "beaches"],
    bestTime: "September to March",
  },
  {
    id: "INTN",
    name: "Tamil Nadu",
    slug: "tamil-nadu",
    kind: "State",
    region: "South",
    tagline: "Land of temple towers",
    description:
      "Dravidian gopurams piercing the sky, the shores of Mahabalipuram and the hill stations of the Nilgiris — Tamil Nadu is southern culture at full height.",
    heroImage: ss("Tamil Nadu India temple gopuram"),
    destinations: ["madurai", "mahabalipuram", "kanyakumari", "ooty"],
    experiences: ["spiritual", "heritage", "culture"],
    bestTime: "October to March",
  },
  {
    id: "INAP",
    name: "Andhra Pradesh",
    slug: "andhra-pradesh",
    kind: "State",
    region: "South",
    tagline: "Coast, ghats and temples",
    description:
      "The sacred hill of Tirupati, the mangroves of the Krishna delta, and spicy coastal cuisine — Andhra is the south's energetic eastern edge.",
    heroImage: ss("Tamil Nadu India temple gopuram"),
    destinations: ["tirupati", "visakhapatnam"],
    experiences: ["spiritual", "food"],
    bestTime: "October to March",
  },
  {
    id: "INTG",
    name: "Telangana",
    slug: "telangana",
    kind: "State",
    region: "South",
    tagline: "City of pearls",
    description:
      "The Charminar, Golconda Fort and biryani that needs no introduction — Telangana revolves around Hyderabad's historic grandeur.",
    heroImage: ss("Telangana Hyderabad Charminar India"),
    destinations: ["hyderabad"],
    experiences: ["heritage", "food", "culture"],
    bestTime: "October to March",
  },
  {
    id: "INMP",
    name: "Madhya Pradesh",
    slug: "madhya-pradesh",
    kind: "State",
    region: "Central",
    tagline: "The heart of incredible India",
    description:
      "Khajuraho's carved temples, the tiger forests of Kanha, and the marble gorges of Bhedaghat — Madhya Pradesh is India's wild, wonderful centre.",
    heroImage: ss("Karnataka India Mysore Palace"),
    destinations: ["khajuraho", "orchha", "kanha"],
    experiences: ["heritage", "wildlife", "spiritual"],
    bestTime: "October to March",
  },
  {
    id: "INCH",
    name: "Chhattisgarh",
    slug: "chhattisgarh",
    kind: "State",
    region: "Central",
    tagline: "Tribal heart of India",
    description:
      "Waterfalls, dense forests and living tribal cultures — Chhattisgarh is central India's quiet, untamed secret.",
    heroImage: ss("Meghalaya India living root bridge forest"),
    destinations: ["chitrakote"],
    experiences: ["nature", "culture"],
    bestTime: "November to February",
  },
  {
    id: "INBR",
    name: "Bihar",
    slug: "bihar",
    kind: "State",
    region: "East",
    tagline: "Cradle of enlightenment",
    description:
      "Bodh Gaya, where the Buddha attained enlightenment, and the ancient universities of Nalanda — Bihar is where Indian civilization found its voice.",
    heroImage: ss("Bihar Bodh Gaya India temple"),
    destinations: ["bodh-gaya", "nalanda"],
    experiences: ["spiritual", "heritage"],
    bestTime: "October to March",
  },
  {
    id: "INJH",
    name: "Jharkhand",
    slug: "jharkhand",
    kind: "State",
    region: "East",
    tagline: "Land of forests",
    description:
      "Waterfalls, Chota Nagpur's plateau forests and tribal heritage — Jharkhand is eastern India's green interior.",
    heroImage: ss("Jharkhand India forest nature"),
    destinations: ["ranki"],
    experiences: ["nature", "adventure"],
    bestTime: "October to March",
  },
  {
    id: "INWB",
    name: "West Bengal",
    slug: "west-bengal",
    kind: "State",
    region: "East",
    tagline: "Tea, delta and tango of culture",
    description:
      "Darjeeling's tea gardens, Kolkata's literary soul, and the Sundarbans' mangroves — West Bengal is India's most cultured river state.",
    heroImage: ss("Darjeeling West Bengal India tea"),
    destinations: ["darjeeling", "kolkata", "sundarbans"],
    experiences: ["culture", "food", "nature"],
    bestTime: "October to March",
  },
  {
    id: "INOR",
    name: "Odisha",
    slug: "odisha",
    kind: "State",
    region: "East",
    tagline: "Temples by the sea",
    description:
      "The sun temple of Konark, the temple city of Bhubaneswar, and unbroken tribal crafts — Odisha is coastal India at its most ancient.",
    heroImage: ss("Odisha Konark Sun Temple India"),
    destinations: ["konark", "puri"],
    experiences: ["heritage", "beaches", "culture"],
    bestTime: "November to February",
  },
  {
    id: "INAS",
    name: "Assam",
    slug: "assam",
    kind: "State",
    region: "Northeast",
    tagline: "Land of the one-horned rhino",
    description:
      "Kaziranga's rhinos, Brahmaputra river islands and satras of culture — Assam is the gateway to the Northeast, lush and warm.",
    heroImage: ss("Odisha Konark Sun Temple India"),
    destinations: ["kaziranga", "guwahati"],
    experiences: ["wildlife", "nature", "culture"],
    bestTime: "November to March",
  },
  {
    id: "INML",
    name: "Meghalaya",
    slug: "meghalaya",
    kind: "State",
    region: "Northeast",
    tagline: "Abode of clouds",
    description:
      "Living root bridges, the wettest place on earth, and hills that disappear into mist — Meghalaya feels like another world entirely.",
    heroImage: ss("Meghalaya India living root bridge forest"),
    destinations: ["shillong", "cherrapunji", "mawsynram"],
    experiences: ["nature", "adventure", "culture"],
    bestTime: "October to May",
  },
  {
    id: "INAR",
    name: "Arunachal Pradesh",
    slug: "arunachal-pradesh",
    kind: "State",
    region: "Northeast",
    tagline: "Land of the dawn-lit mountains",
    description:
      "Where the sun first touches India — monasteries, snow peaks and the tribal valleys of the eastern Himalaya.",
    heroImage: ss("Sikkim India Himalaya mountains"),
    destinations: ["tawang"],
    experiences: ["mountains", "spiritual", "adventure"],
    bestTime: "October to April",
  },
  {
    id: "INNL",
    name: "Nagaland",
    slug: "nagaland",
    kind: "State",
    region: "Northeast",
    tagline: "Land of festivals",
    description:
      "Hornbill Festival, warrior villages and the Dzüko Valley — Nagaland is the Northeast's most vibrant cultural heart.",
    heroImage: ss("Nagaland India hills festival"),
    destinations: ["kohima", "dzuko"],
    experiences: ["culture", "adventure"],
    bestTime: "November to April",
  },
  {
    id: "INMN",
    name: "Manipur",
    slug: "manipur",
    kind: "State",
    region: "Northeast",
    tagline: "Jewel of India",
    description:
      "Loktak's floating islands, classical dance and a landlocked lake country — Manipur is the Northeast's gentle jewel.",
    heroImage: ss("Manipur India Loktak Lake"),
    destinations: ["loktak"],
    experiences: ["nature", "culture"],
    bestTime: "October to March",
  },
  {
    id: "INMZ",
    name: "Mizoram",
    slug: "mizoram",
    kind: "State",
    region: "Northeast",
    tagline: "Land of the highlanders",
    description:
      "Blue mountains, bamboo villages and the cleanest state in India — Mizoram is remote, green and quietly spectacular.",
    heroImage: ss("Jharkhand India forest nature"),
    destinations: ["aizawl"],
    experiences: ["nature", "culture"],
    bestTime: "November to March",
  },
  {
    id: "INTR",
    name: "Tripura",
    slug: "tripura",
    kind: "State",
    region: "Northeast",
    tagline: "Palaces in the hills",
    description:
      "The Ujjayanta Palace, royal temples and the lush green hills of the east — Tripura is small, storied and unhurried.",
    heroImage: ss("Jharkhand India forest nature"),
    destinations: ["agartala"],
    experiences: ["heritage", "culture"],
    bestTime: "October to March",
  },
  {
    id: "INSK",
    name: "Sikkim",
    slug: "sikkim",
    kind: "State",
    region: "Northeast",
    tagline: "The last Shangri-La",
    description:
      "Kanchenjunga looming over pine valleys, Buddhist monasteries and India's first organic state — Sikkim is the Himalaya at its gentlest.",
    heroImage: ss("Sikkim India Himalaya mountains"),
    destinations: ["gangtok", "pelling"],
    experiences: ["mountains", "spiritual", "nature"],
    bestTime: "March to May, October to December",
  },
  {
    id: "INAN",
    name: "Andaman & Nicobar",
    slug: "andaman-nicobar",
    kind: "Union Territory",
    region: "Islands",
    tagline: "Islands in the emerald sea",
    description:
      "Crystal water, coral reefs and rainforest islands — the Andamans are India's most beautiful coastline, floating far from the mainland.",
    heroImage: ss("Andaman Nicobar Islands India beach"),
    destinations: ["andaman"],
    experiences: ["beaches", "adventure", "nature"],
    bestTime: "November to May",
  },
  {
    id: "INLD",
    name: "Lakshadweep",
    slug: "lakshadweep",
    kind: "Union Territory",
    region: "Islands",
    tagline: "Coral atolls of the Arabian Sea",
    description:
      "Thirty-six islands of white sand and turquoise lagoons — Lakshadweep is India's most exclusive and least visited paradise.",
    heroImage: ss("Lakshadweep Islands India coral beach"),
    destinations: ["lakshadweep"],
    experiences: ["beaches", "nature"],
    bestTime: "October to April",
  },
  {
    id: "INPY",
    name: "Puducherry",
    slug: "puducherry",
    kind: "Union Territory",
    region: "South",
    tagline: "The French quarter",
    description:
      "Pastel colonial streets, Auroville's experimental township and a quiet seaside promenade — Puducherry is India's most European corner.",
    heroImage: ss("Telangana Hyderabad Charminar India"),
    destinations: ["puducherry", "auroville"],
    experiences: ["culture", "beaches", "food"],
    bestTime: "October to March",
  },
  {
    id: "INCT",
    name: "Chandigarh",
    slug: "chandigarh",
    kind: "Union Territory",
    region: "North",
    tagline: "The city beautiful",
    description:
      "Le Corbusier's modernist masterplan, the Rock Garden's recycled sculptures and wide boulevards — Chandigarh is India's most designed city.",
    heroImage: ss("Telangana Hyderabad Charminar India"),
    destinations: ["chandigarh"],
    experiences: ["culture", "food"],
    bestTime: "October to March",
  },
  {
    id: "INDH",
    name: "Dadra & Nagar Haveli and Daman & Diu",
    slug: "daman-diu",
    kind: "Union Territory",
    region: "West",
    tagline: "Two coasts, one quiet territory",
    description:
      "Portuguese forts, sleepy beaches and the Silvassa forests — a small western territory made for unhurried weekends.",
    heroImage: ss("Lakshadweep Islands India coral beach"),
    destinations: ["daman", "diu"],
    experiences: ["beaches", "heritage"],
    bestTime: "November to February",
  },
];

export const statesBySlug = new Map(states.map((s) => [s.slug, s]));
export const stateByCode = new Map(states.map((s) => [s.id, s]));

export const regions: { name: Region; blurb: string }[] = [
  { name: "North", blurb: "Empires, deserts and the Ganges plain" },
  { name: "South", blurb: "Temple towers, coastlines and coffee hills" },
  { name: "West", blurb: "Coasts, caves and spice" },
  { name: "East", blurb: "Delta, tea and the great rivers" },
  { name: "Central", blurb: "Forests, tigers and ancient stone" },
  { name: "Himalayan", blurb: "Where India meets the sky" },
  { name: "Northeast", blurb: "Clouds, tribes and living bridges" },
  { name: "Islands", blurb: "Coral, sand and open sea" },
];
